package.json, src/App.css, src/components/configuration/config.tsx, src/components/mainWrapper.tsx, src/components/preview/card.css, src/components/preview/card.tsx, src/components/preview/preview-helpers.ts, src/components/preview/preview.tsx, src/types/configType.ts, src/typings/hero-patterns.d.ts, yarn.lock
=> ✨ Initial card design

src/components/preview/badge.css, src/components/preview/badge.tsx, src/components/preview/card.css, src/components/preview/card.tsx
Fixes: #8
Created card badges using React components instead of shields.io
=> ⚡️ Create badges

src/App.css, src/components/mainRenderer.tsx, src/components/mainWrapper.tsx, src/components/repo/repo.tsx
- Improve spinner styling
- If repo is not found, show an antd notification and just redirect back to the repo input page.
Fixes #16
=> 💄 Better error handling and display

src/components/configuration/config.tsx, src/components/mainWrapper.tsx
=> 🐛 Fixed owner query

src/components/preview/card.css, src/components/preview/card.tsx, src/components/preview/preview-helpers.ts
Fixes #20
Example:
https://deploy-preview-24--github-socialify.netlify.app/CryogenicPlanet/Introduction-to-Scientific-Computing?owner=1&description=1&stargazers=1
https://deploy-preview-24--github-socialify.netlify.app/CryogenicPlanet/UofTHacks-2020?owner=1&description=1&stargazers=1&font=Source+Code+Pro
=> 💄 Truncating description and name

src/App.tsx, src/components/configuration/checkBoxWrapper.tsx, src/components/configuration/config.css, src/components/configuration/selectWrapper.tsx, src/components/footer/footer.tsx, src/components/header/header.tsx, src/components/repo/repo.tsx
=> ♿️ Improve accessibility

.prettierignore, src/components/configuration/config.tsx, src/components/mainWrapper.tsx
=> 🔧 Changed default settings 

public/index.html, src/components/preview/preview.css, src/components/preview/preview.tsx
=> ✨ Add copy buttons

package.json, src/components/configuration/config.tsx, src/components/configuration/textAreaWrapper.tsx, src/types/configType.ts
=> 🐛 Resolved Custom description not in url

.env.example, README.md, src/components/configuration/config.tsx
=> 📝 Update README

package.json, src/components/configuration/config.tsx, src/components/configuration/textAreaWrapper.tsx, src/types/configType.ts, yarn.lock
=> ✨ Back and Forward Buttons

README.md, common/configHelper.ts, common/renderCard.ts, common/types/configType.ts, next.config.js, pages/api/image.ts, pages/api/svg.ts, src/components/configuration/config.tsx, src/components/configuration/inputWrapper.tsx, src/components/preview/__snapshots__/card.test.tsx.snap, src/components/preview/__snapshots__/preview.test.tsx.snap, src/components/preview/card.test.tsx, src/components/preview/card.tsx, src/components/preview/preview.tsx, src/typings/react.d.ts
=> ⚡️ Add svg image

common/relay/environment.ts, common/renderCard.ts, src/components/configuration/config.tsx, src/components/configuration/inputWrapper.tsx, src/components/preview/card.tsx
=> ✨ Svg custom logo

.env.example, README.md, pages/_app.tsx
=> 🔊 Add Google Tag Manager

src/components/preview/__snapshots__/card.test.tsx.snap, src/components/preview/card.tsx
=> 💄 Update default svg size

common/relay/__generated__/repoQuery.graphql.ts, common/relay/repoQuery.ts
Closes #75 
- Will now show only open pull requests and issues
=> 💥 Display open issues and pull requests count

README.md
=> 📃 Update Readme with CLI usage of socialify

.changeset/nine-goats-punch.md, custom-rewrites.js, next.config.js, src/components/configuration/config.tsx
Vercel has been complaining about bandwidth usage.
=> ⚡️ Limit logo to svg to reduce bandwidth usage

.changeset/quiet-mugs-sort.md, src/components/preview/__snapshots__/card.test.tsx.snap, src/components/preview/card.tsx
Add support for new line in description #186
=> Add support for new line in description

.changeset/empty-ghosts-thank.md, README.md, package.json, src/components/footer/__snapshots__/footer.test.tsx.snap, src/components/footer/footer.tsx
Ref https://news.ycombinator.com/item?id=40682711
=> 🚚 Move deployment from Vercel to Netlify

.changeset/flat-bulldogs-occur.md, common/github/repoQuery.ts
#343 https://github.com/wei/socialify/issues/343
=> :bug: Fetch will never throw error when status code is not ok

.changeset/wicked-colts-fail.md, .dockerignore, Dockerfile
=> 📦 Improve docker build process

.github/workflows/docker.yml
=> 👷 Update docker build trigger

.changeset/add-jetbrains-mono-font.md, common/types/configType.ts
- add JetBrains Mono to font enum
- document the change in a changeset
=> Add JetBrains Mono font

.changeset/witty-flies-admire.md, app/api/graphql/route.ts, app/api/png/route.ts, app/api/stats.svg/route.ts, app/api/stats/route.ts, app/api/svg/route.ts
The previous headers were fine. Fixed configuration error in Cloudflare.
=> ⏪ Revert "⚡️ Update cache headers for better cache hits"
